Import("env")
cenv = env.Clone()
LIBS = ["main_cxx", "armadillo"]
cenv["LINK"] = env["CXX"]
# python SOURCES = ["main.cpp"]
# python cenv.Program("main", SOURCES, LIBS=LIBS)

# python SOURCES = ["main_gems.cpp"]
# python cenv.Program("main_gems", SOURCES, LIBS=LIBS)

# python SOURCES = ["test.cpp"]
# python cenv.Program("testcxx", SOURCES, LIBS=LIBS)
#cenv.Append(CXXFLAGS=["-DENABLE_CXXOPTS"])
SOURCES = ["generate_modes.cpp"]
cenv.Program("generate_modes", SOURCES, LIBS=LIBS)

#LIBS = ["main_c", "main_cxx", "armadillo"]
#SOURCES = ["test_deim_cxx.cpp"]
#cenv.Program("test_deim_cxx", SOURCES, LIBS=LIBS)


LIBS = ["armadillo", "lapack", "blas"]
LIBS.append("rom")
#env["LINK"] = env["F90"]

#LIBS.append("main_fortran")
if GetOption("intel_mpi") or GetOption("intel"):
    LIBS.append("intlc")
    LIBS.append("ifcore")
    LIBS.append("ifport")
    LIBS.append("stdc++")

else:
    LIBS.append("gfortran")
    
#SOURCES = ["test.f90"]
#env['STATIC_AND_SHARED_OBJECTS_ARE_THE_SAME']=1
#env.Program("test", SOURCES, LIBS=LIBS)
